### ISSUE TITLE
Write a bot which changes current revisions

### ISSUE THREAD

**Issue by kulla** [serlo/serlo-bot#7]
We should write a bot which we can run regularly (maybe once a year) which does certain jobs in formatting Serlo articles like:

- [ ] serlo/api.serlo.org#1681 
- [ ] serlo/api.serlo.org#1680 
- [ ] serlo/api.serlo.org#1679 
- [ ] https://github.com/serlo/serlo-bot/issues/8

**Comment by hugotiburtino** [comment]
We shouldn't have a bot for that, it has just to be saved correctly.
Anyways, I transfered the issues to `serlo/api.serlo.org` in order to make migrations for them in the future. The code for the migration can be repeated once in a year if necessary
